### ISSUE TITLE
transparent pngs printing as black

### ISSUE THREAD

**Issue by Erreinion** [aginiewicz/createspace#5]
Reproduced with the following code:

    \documentclass[11pt]{book}
    \usepackage[size=novel,bleed]{createspace}	
    \usepackage{graphicx}
    \DeclareGraphicsExtensions{.png,.jpg}
    
    \begin{document}
    \includegraphics[scale=0.5]{sample}
    \end{document}

The colour portions of the png print fine, but the transparent layer prints as black. Problem goes away when the createspace package is commented out.

**Comment by aginiewicz** [comment]
I think this is because transparent pngs are not allowed in PDF/X-1a iirc, so when setting the requirement to output file that validates, it can behave in unexpected ways. You have to use png without alpha - or if you want to use transparent background (0-1 transparency) switch to vector graphics, especially TIkZ. There is application svg2tikz (https://github.com/kjellmf/svg2tikz) that I used to convert SVG files (for example from Inkscape) to TikZ with great success. What exactly you need transparency for?

**Comment by Erreinion** [comment]
Thank you for the explanation. The images I was given have transparent layers. Converting to jpg lowers the quality, so I was hoping to get the pngs to work. I will work on different conversion options.
